# Generated by Django 2.0.2 on 2018-04-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientID', models.IntegerField()),
                ('Address', models.CharField(max_length=500, null=True)),
                ('Contacts', models.CharField(max_length=500)),
                ('CreateTime', models.DateTimeField()),
                ('Remark', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('IDCard', models.CharField(max_length=20)),
                ('YBCard', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('WeChat', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=10)),
                ('FingerPrint', models.CharField(max_length=1000, null=True)),
                ('PassWord', models.CharField(max_length=18)),
                ('Cipher', models.CharField(max_length=6)),
                ('CreateTime', models.DateTimeField()),
                ('LastLogTime', models.DateTimeField()),
                ('Remark', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugStore',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('ManagersID', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500, null=True)),
                ('CreateTime', models.DateTimeField()),
                ('ModifyTime', models.DateTimeField()),
                ('Remark', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
