# Generated by Django 2.0.2 on 2018-06-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0002_address_clients_drugstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medi',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=2000)),
                ('ProducerID', models.IntegerField()),
                ('GuidePrice', models.DecimalField(decimal_places=2, max_digits=2)),
                ('DoseUnit', models.CharField(max_length=20)),
                ('DoseFactor', models.IntegerField()),
                ('OtpaUnit', models.CharField(max_length=20)),
                ('OtpaPack', models.IntegerField()),
                ('InpaUnit', models.CharField(max_length=20)),
                ('InpaPack', models.IntegerField()),
                ('HouseUnit', models.CharField(max_length=20)),
                ('HousePack', models.IntegerField()),
                ('Instructions', models.BinaryField()),
                ('CreateTime', models.DateTimeField()),
                ('ModifyTime', models.DateTimeField()),
                ('Remark', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Dept',
            field=models.ForeignKey(on_delete=True, to='basemodel.Dept'),
        ),
        #migrations.AlterField(
           # model_name='doctors',
          #  name='Organization',
         #   field=models.ForeignKey(on_delete=True, to='basemodel.Organization'),
        #),
    ]
