# Generated by Django 2.0.2 on 2018-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0003_auto_20180613_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('CreateTime', models.DateTimeField()),
                ('ModifyTime', models.DateTimeField()),
                ('LastChange', models.CharField(max_length=100)),
                ('Remark', models.CharField(max_length=200)),
            ],
        ),
    ]
