# Generated by Django 2.0.2 on 2018-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0004_baseobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='CreateTime',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='ModifyTime',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='Remark',
        ),
        
    ]
