# Generated by Django 2.0.2 on 2018-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodel', '0005_auto_20180716_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='Organization',
        ),
    ]
