# Generated by Django 2.0.2 on 2018-07-19 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default='default code', max_length=10)),
                ('Name', models.CharField(default='default name', max_length=10)),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('ModifyTime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('Remark', models.CharField(max_length=1000)),
                ('CompanyName', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=100)),
                ('IntentionalProducts', models.CharField(max_length=100)),
                ('PurchasePoint', models.IntegerField()),
                ('FollowRecord', models.CharField(max_length=1000)),
                ('ProjectProcess', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=1000)),
                ('Clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelationClients', to='crmapp.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default='default code', max_length=10)),
                ('Name', models.CharField(default='default name', max_length=10)),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('ModifyTime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('Remark', models.CharField(max_length=1000)),
                ('Phone', models.IntegerField()),
                ('Role', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('WeChat', models.CharField(max_length=100)),
                ('QQ', models.CharField(max_length=50)),
                ('Email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='crmapp.Client')),
                ('Contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelationContacts', to='crmapp.Contacts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default='default code', max_length=10)),
                ('Name', models.CharField(default='default name', max_length=10)),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('ModifyTime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('Remark', models.CharField(max_length=1000)),
                ('RecordText', models.CharField(max_length=1000)),
                ('Contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactsRecords', to='crmapp.Contacts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(default='default code', max_length=10)),
                ('Name', models.CharField(default='default name', max_length=10)),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='新建时间')),
                ('ModifyTime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('Remark', models.CharField(max_length=1000)),
                ('PassWord', models.CharField(default='123', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='followrecord',
            name='RecordUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Records', to='crmapp.User'),
        ),
        migrations.AddField(
            model_name='client',
            name='Contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientContacts', to='crmapp.Contacts'),
        ),
        migrations.AddField(
            model_name='client',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='crmapp.User'),
        ),
    ]
