# Generated by Django 2.0.2 on 2018-06-14 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Cipher',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='Code',
            field=models.CharField(default='0011', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='CreateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='FingerPrint',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='IDCard',
            field=models.CharField(default='511028199006201814', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='LastLogTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(default='firstlogin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Remark',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Sex',
            field=models.CharField(default='男', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='WeChat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='YBCard',
            field=models.CharField(default='yb110', max_length=20),
        ),
    ]
