# Generated by Django 2.0.2 on 2018-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180614_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PassWord',
            field=models.CharField(default='123', max_length=18),
        ),
    ]
